name: secure_note
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  get: ^4.6.5
  hive: ^2.2.3
  # isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.0 
  cryptography: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # hive_generator: ^1.0.0  # no soup for me
  # build_runner: ^2.0.0


flutter:
  uses-material-design: true
